# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: NK
brief-intro: DevOps Data Engineer
# >>OR use baseurl and url to deploy this site remotely/github
baseurl: "/Myblog"                  # "/Myblog" # the subpath of your remote site, e.g. /blog
url: "https://nilskuhler.github.io" # the url hostname & protocol for your remote site
# >>OR use baseurl and url to deploy this site locally
##baseurl:                              # The baseurl should be empty to run locally. DO NOT USE ""
##url: "https://nilskuhler.github.io"   # The url should contain this "https://nilskuhler.github.io"  content otherwise mobile menu does not work. 

permalink: /:year/:month/:day/:title/

# other links
twitter_username: 
facebook_username: 
github_web: https://nilskuhler.github.io/mygithub/
github_username: NilsKuhler
email: 
weibo_username: 
zhihu_username: 
linkedIn_username: nilskuhler
dribbble_username:

description_footer:

# comments
# two ways to comment, only choose one, and use your own short name
# 两种评论插件，选一个就好了，使用自己的 short_name
duoshuo_shortname: 
disqus_shortname: 

# statistic analysis 统计代码
# 百度统计 id，将统计代码替换为自己的百度统计id，即
# hm.src = "//hm.baidu.com/hm.js?xxxxxxxxxxxx";
# xxxxx字符串
baidu_tongji_id: 
google_analytics_id: 

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

# port
# port: 1234

# url
category_dir: category/
tag_dir: tag/

# excerpt
excerpt_separator: "\n\n\n\n"

# paginate
gems: [jekyll-paginate]
paginate: 6
